import Head from 'next/head';
import Image from 'next/image';
import withLayout from '@Components/HOC/Layout';
import styles from '../styles/index.module.scss';

const HomePage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        NAM DAI NHAN
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
export default withLayout(HomePage);
