import Head from 'next/head';
import Image from 'next/image';
import withLayout from '@Components/HOC/Layout';

const HomePage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      </main>

      <footer>
      </footer>
    </div>
  )
}
export default withLayout(HomePage);
